replicaCount: 4

image:
  repository: yashikapaul/eventpulse  # ← Change this
  pullPolicy: IfNotPresent
  tag: "81"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 15

readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10
